Repository prakticas/urlshortener, pull requests merged in 2021-11, with the labels that each got.

#5 Interfaces del servicio y sus tests
  app/src/test/kotlin/es/unizar/urlshortener/IntegrationTests.kt
  app/src/test/kotlin/es/unizar/urlshortener/QRIntegrationTests.kt
  app/src/test/kotlin/es/unizar/urlshortener/QRUnitTests.kt
  build.gradle.kts
  core/src/main/kotlin/es/unizar/urlshortener/core/Domain.kt
  core/src/main/kotlin/es/unizar/urlshortener/core/Exceptions.kt
  core/src/main/kotlin/es/unizar/urlshortener/core/Ports.kt
  core/src/main/kotlin/es/unizar/urlshortener/core/usecases/QRUseCase.kt
  delivery/src/main/kotlin/es/unizar/urlshortener/infrastructure/delivery/ExceptionHandlers.kt
  delivery/src/main/kotlin/es/unizar/urlshortener/infrastructure/delivery/QRController.kt
  delivery/src/test/kotlin/es/unizar/urlshortener/infrastructure/delivery/QRControllerTest.kt
Labels: v1, QR

#8 Qr service
  app/src/main/kotlin/es/unizar/urlshortener/Configuration.kt
  app/src/main/resources/static/index.html
  app/src/main/resources/static/js/app.js
  app/src/test/kotlin/es/unizar/urlshortener/QRIntegrationTests.kt
  app/src/test/kotlin/es/unizar/urlshortener/QRUnitTests.kt
  build.gradle.kts
  core/src/main/kotlin/es/unizar/urlshortener/core/Domain.kt
  core/src/main/kotlin/es/unizar/urlshortener/core/Ports.kt
  core/src/main/kotlin/es/unizar/urlshortener/core/usecases/QRUseCase.kt
  core/src/main/kotlin/es/unizar/urlshortener/core/usecases/RedirectUseCase.kt
  delivery/src/main/kotlin/es/unizar/urlshortener/infrastructure/delivery/PortsImpl.kt
  delivery/src/main/kotlin/es/unizar/urlshortener/infrastructure/delivery/QRController.kt
  delivery/src/main/kotlin/es/unizar/urlshortener/infrastructure/delivery/QRController.kt.kt
  delivery/src/main/kotlin/es/unizar/urlshortener/infrastructure/delivery/UrlShortenerController.kt
  delivery/src/test/kotlin/es/unizar/urlshortener/infrastructure/delivery/UrlShortenerControllerTest.kt
  repositories/src/main/kotlin/es/unizar/urlshortener/infrastructure/repositories/Converters.kt
  repositories/src/main/kotlin/es/unizar/urlshortener/infrastructure/repositories/Entities.kt
  repositories/src/main/kotlin/es/unizar/urlshortener/infrastructure/repositories/PortsImpl.kt
  repositories/src/main/kotlin/es/unizar/urlshortener/infrastructure/repositories/Repositories.kt
Labels: v1, QR

#9 QR hotfix
  app/src/main/resources/static/js/app.js
  app/src/test/kotlin/es/unizar/urlshortener/QRIntegrationTests.kt
  delivery/src/main/kotlin/es/unizar/urlshortener/infrastructure/delivery/UrlShortenerController.kt
Labels: bug, bug-minor, v1, QR

#10 Masive shortener
  app/src/test/kotlin/es/unizar/urlshortener/QRUnitTests.kt
  build.gradle.kts
  core/src/main/kotlin/es/unizar/urlshortener/core/Domain.kt
  delivery/src/main/kotlin/es/unizar/urlshortener/infrastructure/delivery/MasiveUrlShortenerController.kt
  delivery/src/main/kotlin/es/unizar/urlshortener/infrastructure/delivery/UrlShortenerController.kt
  delivery/src/test/kotlin/es/unizar/urlshortener/infrastructure/delivery/MasiveUrlShortenerControllerTest.kt
  delivery/src/test/kotlin/es/unizar/urlshortener/infrastructure/delivery/UrlShortenerControllerTest.kt
Labels: enhancement

#16 massive shortener frontend
  app/src/main/resources/static/index.css
  app/src/main/resources/static/index.html
  app/src/main/resources/static/js/app.js
  delivery/src/main/kotlin/es/unizar/urlshortener/infrastructure/delivery/MasiveUrlShortenerController.kt
  delivery/src/test/kotlin/es/unizar/urlshortener/infrastructure/delivery/MasiveUrlShortenerControllerTest.kt
Labels: enhancement, v1

#20 qr añadido al amsive
  core/src/main/kotlin/es/unizar/urlshortener/core/usecases/CreateShortUrlUseCase.kt
  delivery/src/main/kotlin/es/unizar/urlshortener/infrastructure/delivery/MasiveUrlShortenerController.kt
  repositories/src/main/kotlin/es/unizar/urlshortener/infrastructure/repositories/Converters.kt
  repositories/src/main/kotlin/es/unizar/urlshortener/infrastructure/repositories/Entities.kt
Labels: bug

#14 Nivel 10 QR asíncrono
  .gitignore
  app/src/main/kotlin/es/unizar/urlshortener/Configuration.kt
  app/src/main/resources/static/js/app.js
  app/src/test/kotlin/es/unizar/urlshortener/QRIntegrationTests.kt
  build.gradle.kts
  core/src/main/kotlin/es/unizar/urlshortener/core/usecases/QRUseCase.kt
  delivery/src/main/kotlin/es/unizar/urlshortener/infrastructure/delivery/ExceptionHandlers.kt
  delivery/src/main/kotlin/es/unizar/urlshortener/infrastructure/delivery/QRController.kt.kt
  delivery/src/main/kotlin/es/unizar/urlshortener/infrastructure/delivery/UrlShortenerController.kt
  delivery/src/test/kotlin/es/unizar/urlshortener/infrastructure/delivery/QRControllerTest.kt
  delivery/src/test/kotlin/es/unizar/urlshortener/infrastructure/delivery/UrlShortenerControllerTest.kt
Labels: enhancement, v1, QR
